spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: redis_db
    port: 6379
    password: 7rlTkxmqnrredis6379

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 6f793b774eae1875718d4facb0f67df2
            client-secret: ddIOO9n0Wc5uOKS9c1iibqWOLFOK3Gvs
            redirect-uri: http://j7c101.p.ssafy.io:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: cb3b8f5a853df90748cfcf5e2980c28db0c932e0dbf7d0686bc211e155324f6f85926583b183a57e7e91939666a2242b7c776c1420d2a28b073cae39c7373508
  access-token-validity-in-seconds: 43200
  refresh-token-validity-in-seconds: 86400

front:
  url: http://j7c101.p.ssafy.io:3000/oauth/callback

logging:
  level:
    org:
      hibernate:
        SQL: debug
